"""Added indexes and composite unique constraint to ModelMetadata

Revision ID: 83c654b8f6ec
Revises: 9d43f4ef75d0
Create Date: 2024-09-25 02:50:15.812624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c654b8f6ec'
down_revision = '9d43f4ef75d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_metadata', schema=None) as batch_op:
        batch_op.drop_constraint('model_metadata_model_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_model_metadata_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metadata_version'), ['version'], unique=False)
        batch_op.create_unique_constraint('unique_model_version', ['model_name', 'version'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_metadata', schema=None) as batch_op:
        batch_op.drop_constraint('unique_model_version', type_='unique')
        batch_op.drop_index(batch_op.f('ix_model_metadata_version'))
        batch_op.drop_index(batch_op.f('ix_model_metadata_model_name'))
        batch_op.create_unique_constraint('model_metadata_model_name_key', ['model_name'])

    # ### end Alembic commands ###
