"""Add nullable merkle_root column with default value

Revision ID: b6c595a00c2e
Revises: 
Create Date: 2024-09-24 00:48:56.045021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c595a00c2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merkle_root', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_metadata', schema=None) as batch_op:
        batch_op.drop_column('merkle_root')

    # ### end Alembic commands ###
